package main

import "fmt"

func main() {
	fmt.Println(findTheLongestSubstring("vajsdzaxodxrquzrorcisoluxuvqjjtnqoxeqmkzxavcvzigbtdeoupeaxrwvmwmkakssyantkfncgyymjsxzdgdmfiivivdphgyzfxzzbohboqinxkuakbfmbkjkcmndfvhcbkejdfebthjjpmhhmqglloqmgbohyxbzoaqvhjfnwzzkekyrhtoujujjiqibvoqivhuoaszuoodknxgdzzntcjweiphbbskbqtyxkbocneswavlukdxpjushdylmhqeniexfcnjccbedefitvimlbsqqgqvgipfryentxtcupuibvqrlwltkyibnmeyqmauejjctwnpjhfoihfrfqfzjfjsnnzvqiiwrflnlgibxrerhcngcphmkujslvafrqxguduaiwpnupjpsvsymfldsibhhonnmuipjzvictawhehixuhlacbzbgzyhxcsvstjpqsisswnaypgnzttmaoqitkdrdzeqtaiizcqcquqtcvrxfbltgamditwtkxlmqrryzxwfpuaglejpurmwnocztqmkzjmdnrdrrtdjzezpvytpibojwdlcbohotigndowiougijfmxyvepgcbttonxtrruaogjfurlzmoplbihbkrvxgohwtndnurtzsqxnccxvrcbpslfljhihudfmjtvqqdojwyuycnqrerjfhzmdcesvntkpunaahsgxtkckwqldoruigypnthpatvaeladuvdfqazqyjrugqphxiydkbnztdphwhhridlloqdsrlsklinwrltrgrmyysrnvrccpnrfxsubskjdhuywwakyfnhkzzjecwxxywensyxodzogfrbdbbpruxftedtttqxmqzmubsvtwmbjvvcmatktbuexxtcoxxhklevaqbufkuqjubfasppnandszgxgksvngvfceebzmzvxczprgrzaztoyaikkatuxtthohocygeujxblzwqqgnfdkbyucljrzzxbsseixoibimnkxavhypfbjizhgdbnyoflplskcffnipxzzfnjxhmtigmlvfjcpvmkuggaceijfdiygamspablbewnprgphxiwtrjfacmgfycpmtinqtyltedihsfzrlpdhpixrezpnfpzchslxtblfgcchmrbpaxwfgczeaozaqdccttiezoepiwklrxdzttqerboukqxctbznotmzrknaidhbjoscyvooqgjtkpbkronsbgpwpeadaizfkuttdcuzcuduabubjfunhdfuqrnzzanmicurayevloptssqjhrzmcvmadnldbdebuxjvqrrjdaqdzmjnliiwabcopesurqnzmvjyrpeuzdylwdfuiefwiqctuwncqruaifgblcghikavgtrbcsbzjgflwsrhmgvoabbvnwdpwfutqopzkohqdnchskmmgrcwdjqqxoiymucwgclzzbumluaqvlpvcnhawxrynuihlvhqocakmupphnurggrtlzrofkfkvumjlexdcbcsdomlmtgczdoxoawcqubsjsgmlpsxywyzkwxnmbkiejqzpxjbzscdyumlkgxgyfubfwvcdaxjhnrqenptdlwxkqojrttwgmfceiakmloktiwmsxhktcovohqyhjwcswlvpfksvsttgnnaqumgozmrtfzbbakscltmgtwlojcicowyrfwncaozdlypprbgczghwziqcyfrkqfbruvamydltxndgsotgprjkzlliawkutiepyjyvyhcjlqkgvmxmhfsbmioywzbmmyagutwswpvlvqrwpxuwuhvuvcpvemqwifarabzujyumjwsenuimxntljtpjzhnujqxsujzmzalqgksykytnvsmbrjvfmbanbjxjnzoblexhawxyztbagaidjyvvvspatgtnuogxdnvohoijsvisrjafyiwrsqybkjfgqdeutzooprrwzkicnjjcmhphkygoztuxjqwgcokliosfaennnzcmfekgpcjjshlwhefzukpquckjvkqkgbmdvdvlzgkcqzidriguyztzvmwoormvrqfirqnpmxtkdpoebixfrjbmjyzdgafucnzhgqhgtmffjjmartvervejrndnvyqwvrsossdxyedohoxjpcusftslixxdzqqmenawihmencnfjnxqmbdlzjkchzzbrfzpgimorjcwtolirihvsdwdshifpbcbbrquiyemtuqejyzkkecvpknipkovlulxrufugjyzzelucbnmnuwstyplwjhwcdfrbcjdoozslqynlnfkzynrfarhzcvjualuehvnosynesznnvmpjdlhcuhhzrrhuhpuacqnmdcmjbtksyjdrgrqnnvukdhbmcuhmivianumvjflxpmgzuafnqerkiyqsnqkhhyzxkroyohtuqonrhsofctajiwwoiiqptemrakynhceisjwzvucrryhxsfznepximftmrcbuxkvezxhbfbckwhcpmebphutbmvpidilmkbudesfixoccqsbogrcptizjzmfsifeyxiuvbineurlibjatooiktscsnscwntfgzkregyuopcotahekrejlgmlwjxiofayutpqzntsfnrkoztcvkzvwkxpnozqgiliiewhjsqjcbiscrisjplvwvwiqpxzkqceidqlhvkmddpzovpwswicyenugneqonhdjnnybvrbrovzbstvlvzptpwzmjdikztkyxkvarvposeztlzqxfbseyyfomyqsvksfuxiatjlgvklgyhqtjsrdfinfxltzkggdphrqqjigyazvyqnvinrjhgcouulklejvalvfezhybvgydlcxerqardtzraqnyawxukrevohjarilfglrlttunjvcnhnxzckhbtevuhcosuspzyxnhjfyuhmuczcgmuiwdvkodfxsacgikwslmbakdvbufliipqsjtfvrubodsprjgrxedvkkepkrhshwzmfzwqpixmfssgmaqgkkckmcgktzzigxjgwapjnfhbdphjeyeqyqcrzypdvkvbzmyzfzyrkjcqgqgttgpgxqbfodzvdkxkuuigmsbdbzagcdbxlcgaoahcygdldbeqjbnqgqffzctdkuzhvutnhotwwuagajtfwnhsifoagmjgvcjtxtbhkdpkcplskbamioidwhtxuimmtvuqyfneeahbyisgpdsppngdrfiabecantkgbibbhvglkxdbyqeyrzrjfowacqyfxrxaaubnokjpzykakrklirjvvwmhkdljrptwrpuylrflknsimdkxagjwcnueywtchdwphtxbzziprwbbrnxqoutmpzmdnpjhxumgipkbddhtqgiwipklrcomvikpjzpxjorhkrkglpyrqgrxfblwjhsigzjoivbxendyiphjrgliiwcbutqdvrnkeazqswdzckphjotzswzgpaexxxblzgxrxchhoxyrccabzpecjoyyawsuthzjaoopyrvyaaggjynbrkkgkaxutaywdafpwdxqiyoxujfpsklmitsuejjfuqzpljnsdgcdisjltrtogbqkkcclddmxsbtxodbchucxujvbodpdbgihpblwtynlktyhivcqzocwjadkghieunfobqlzkfvorxfsizoztphhvixfkoruvrbaflicjbhdwlqikozjyjlzypwcelvlfzcftxzlgfzaxnzttsukrxpmhkoypvagwprdfxkotedqxqmtqnfizacdatharhmkvsjjdaqfeufjropxtxyvthbnxrjjgaiuepjkydlgkxpfpllcthkijkntuwytcfwfstcxhnqjtryrktohbugkjlkdawoypqozslwmerknhblstdrsfgqtrmkfefiueschmbmidtouujpjrhhbtwzbtqvtdpugoaulkswacaxtpoksnousgjgnfvusmkeeoqceadapjqthqkictaytthpkgahwfsemnunlrwsixxdgdaxxmnisjsuuubsrdkesvhxxjibkxybxrkafdfflajwtsounxiqoulafkugsmooxkiylqgrgpjfxvsxxqssnyqyhmydaydhhenkplyeuzcacwgzrxaheyhzidddiklvysgwgkgjpgsilzyqfkzwdrgcpxxkxblqofiqkziebzwchlimwmywotvrsoywrevgcvdsoxrpmequgbqdxirldjccepypnxvfutbghqkrzrphalafjeiiqolmwncfogjzazqzqvhelmneknxvwizzmuhkgpyunlbzzhvhgnumemcitrmcxvkazktmjbthajqlrxxntnzkxfouxhioratppdmomcubfmbrqzdntkfwkheolqwoaithdlzcsjhblrstfrnnhpokeosbwlhzsaeaedklxjmfzyjgixdytipzperkkjcgovcmdrpscoexdbqnryhztufqqpvfowwdimddncsylgnoustuiobokbwnxxywyguuwluqkxhyjmrtnfratfbsbvgsyejiwrbbivscrzbkgvcpbkisqvdvovkfhgcyqhwgdepghlcxpdeteksndcpomtdnqpchlxxdznoexfqttehmpmmmlfwoaeaogslsnvpgbuefqbwbnfchsxdhshjhctlojzfblkmlgacsnorgktobehatzyteutbeugoattemaitcdyicrkncsmofalnkvdtguxrnibxgeannlqhoigcwwszunkqtfeermszvmbalpnfyzvqinjereeblkxcvcpaeilsladmyadjzjjfcahdzbuerwpgpmcsrazttzthyrdcyalywjtdksttykfmuclpsyynkxoforgedkvvvvxncngmjqdyfohtueeujemcuchixhdthuwxnrapsilwyuaebvobzmjelundeondtcwlswyvdxjebyyeueyobrfrbrrsujnjywnxcapjznzihaeaeunidzplziewvbxrrsimbwrlhmtoqarpwyreqttgiqtaebgjxottwitqwibznmojuqukrqxrrnuzehvuxbpmhcouyqjrviuumqaeohwqoouktghtmeudwpihgtjxvtmtjxoonngvemmorcrrkckwnytlermkxzuffygljhlqgyxhndicxeofsrlcdzoqswtqwemhxbtzufzuaqpesaerasdzuukgjzjauvwqcigzydcpbljhpxxxeuttozbixbuczwjovrfxmmwaekydifffcxnxcqpyvskekqwsbjgseflunfvguaoxummtqioepdcnqjwtcnjxyaliygfejhnevdfmglaucnzgpvaxyblzrbgechsvxudxykfmeknojreuzwziesvqnlhnlybfkkskczstlcfgciozbamfbpjlwwqtnmatfjtfpnwopdqgdqxtjfsmmnvwqxzrzqtuhtkgcfxgldgwzsqfemigtnmntnhlwodrtnwpwfubwdqtrcauplzcdnuhzxcbqxbdbelwnqbgwxubxqiowltmmhrzdsbkwfasofcxduvnmloevkhsqjotnnlsfitzerukhvcdzdhfxsknuodwypeixomtriqnndwpsbxzqnhsylsvvgnveyosxhnlsvtozuroictfftgpppwqsugtmfeiaosnrxtekaxfvmmrrpsidvgacsumqsxtdimtttrmgszrjfqigquepbjfdiborpbdlyrtxesozcizmutztzryjalyvtenurbwrkqdpfzjqmodktzwbldciboswxjezxxaalzzucyeghcfzikklziirxhchjtauftudxdylenwqxzpcpuaiccnotseylzjzkihdwhodrvfaquzupbirflqbwrmzngjtgmhuobsjugvvpvzvtnfnxrokdcuktkfrlidubrqjfmcrlknfvwjmbwojfveseumkydnfsazsheqikrqtprrjehvcfydymcrxcpgppaidbgkrlxtbrupleijtlarbfvmaokjxygltbzuwwthjcevgxbxcergenvgrymborgqqrprfjljkekgocqnobcskfuesdhqyjkrglbroyynrcqpmbfpsqfkqcffvhopqfqzrpcyxlqibirkiiilctndgdgradhvhqyipiykewdhijysecihzweaamzjheouhudbvekznvsmdnycraygznhssjhruicryocefpwlnvqjrdkbkeixgonyzekcajydhpqndkhapivifhzvydvqupavrtcuwxdupegqnvdrnkblkzdahwvfbziyklmunssjazrewnwbwmfxqybdceudykvqrhhzefwfpfrhiyzjqwvyxpvkfyowiawlqutdbtkewofqukhyskgntrlkxddcrqgnbncehnewqeuzoewehremhsrgbokavbcbogjbvqrzasetwxlepuetdaeqmkvhsbtaubmojwdhpjopwanjhoduggtffsrtbzrqbnojmsjkzeahprgekuwfizmymkcpgxolspmfekscaxvomrbsjmserulyuxueugjutortoemqqwktakkqhwylikjefcovfthmsfyaxqhozvuchucoubdyxxdpourukzjtbarbwtywgxovbglzjsepqmfdtvpumkyfqudiqdiudiztvpucytugtmqtbbowlicjjgklimykrkpylwuuomqwftghyijztuozeiuktqrcewegimpgohoixpkyidokkqlavctrkokpawrkngvmxglqvblzwikfasiqmkxayzszembjwemmoekxnqimcvruinjaxycofdysfkfrrfsisbuuljsutixcnixcekostehvdnnxtbjqpeubtjmztapuuobrymqyrtykvfsqokuqrrwnowyqjeafpyjwfxbcbmhoxmjctdtklmbbgfrereybajgfdbgxfkrlvoetqbrarthytdqjpaqrherzltprtbeyudakbysrleabrxeewxvwdcefrzmlkeaznpmdfftcxcgzjsrdodpvpscfevyiohmuqwwhwpzytaakhicsvmdksgwdtcchsqudtosyfwqtvmuedwhpwlpokljzrdkmxffmlsmjwyxnsgzjaigywjumvrandmirxeqjmafxjqubkyjlrtgxcyoqcacfrjimvmecdxsntbtwrkhcwcjkwfrlviweznxguehidpfgyenurhdzgegwlhcjxhuehzhicifjbhhirdxjcrexsmfcoifcxbfziexgxsxtlrtcnwqyrwpsrjnyinxpwjtqjeglipmvssuqmzarmqtrzpgokaoayznaylwnjkmumpgejtmrnbrfqxbwadshvmmpirvyfreiswwnkijkvtxjwhcdknmrarjezjcivcleyznctmenevyphnuwacfypgasnhngvozjdaumylatsfzcputfvsepcmrpbbzkrorokeitsbrhleflarqnhbdwknbruukfhtszbifsdgdevokxdhsvopnucakxfezhmefdikgbmivebdwntfkcaccirzwbmfcmzqkbwzlfybabxegliadnsujyerdkgqravsudjphnzfxupkjndhraguqrlxihgvdmgjgkjzweuwmndsvgfajrqwxzuefjtocaiyuqxfhcpkxrdbwkzgmaqgoeavhplknuvmlnfypxewbhezkqganmkladbghulhbsjfjbzlimzlvxrbghzsijigqweigqqbuwwaiprhqvfklsjtfnjpjunlzvfjvotlozuaujwmjxcvtlvohpjqkmexmaoteckylkluiiiipvuzmmlfqvbfelscbpiieerlgdpvctheliitbnlxakqwfhfoctakabuxumijmosjlpnsiifomluzziazzkuqhgkpxlhyefvlzibujtphxwtpfwmeokddzyyfazvogulbpxjrmixtemqhuafystviiojvxvnveagigsxvuaqfbayjpfgfcjefjlnklugybinwtheomzfazetscgzupaawplxnslwnbjsdmkzfcxdiuzesshdcxcoagakutsjvnxdleqltgiqubadflsqvdtaqejucnacxitwqttzzphssrvklzwhwbiwixcnqlhdmvuysywmiquilvbawvsxycxkggfjgqkmjmvhjfnwpfupnnkxzlczjuicheoenkwnkfhgjrndslukpunvkakdlazyrojusilluurbcaklmstogrtgktbygfxuqosrrmgqixulltknguawwaeumbqdmjvbyarnpbmtjzrdtzn"))
}

//试题地址：https://leetcode-cn.com/problems/find-the-longest-substring-containing-vowels-in-even-counts/
func findTheLongestSubstring(s string) int {
	//处理a e i o u
	numStr := make([][]int, 5)
	for i := 0; i < 5; i++ {
		numStr[i] = make([]int, len(s))
	}
	maxLen := 0
	for i := 0; i < len(s); i++ {
		for j := i; j < len(s); j++ {
			if i == 0 {
				switch string(s[j]) {
				case "a":
					getNumStr(&numStr, j, 0)
				case "e":
					getNumStr(&numStr, j, 1)
				case "i":
					getNumStr(&numStr, j, 2)
				case "o":
					getNumStr(&numStr, j, 3)
				case "u":
					getNumStr(&numStr, j, 4)
				default:
					getNumStr(&numStr, j, 5)
				}
			}
			if isTrueString(numStr, i, j) {
				maxLen = max(maxLen, j-i+1)
				// fmt.Println(i, j)
			}
		}
	}
	return maxLen
}

func getNumStr(numStr *[][]int, i, j int) {
	if j != 5 {
		if i == 0 {
			(*numStr)[j][0]++
		} else {
			(*numStr)[j][i] = (*numStr)[j][i-1] + 1
		}
	}
	if i == 0 {
		return
	}
	for k := 0; k < 5; k++ {
		if k != j {
			(*numStr)[k][i] = (*numStr)[k][i-1]
		}
	}
}

func isTrueString(numStr [][]int, i, j int) bool {
	if i == 0 {
		if numStr[0][j]%2 == 0 && numStr[1][j]%2 == 0 && numStr[2][j]%2 == 0 && numStr[3][j]%2 == 0 && numStr[4][j]%2 == 0 {
			return true
		}
	} else {
		if (numStr[0][j]-numStr[0][i-1])%2 == 0 && (numStr[1][j]-numStr[1][i-1])%2 == 0 && (numStr[2][j]-numStr[2][i-1])%2 == 0 && (numStr[3][j]-numStr[3][i-1])%2 == 0 && (numStr[4][j]-numStr[4][i-1])%2 == 0 {
			return true
		}
	}
	return false
}

func max(x, y int) int {
	if x > y {
		return x
	}
	return y
}
